#ifndef __GLOBAL__
#define __GLOBAL__

#define NUMBER_OF_OBJECTS 10
#define GENESIZE NUMBER_OF_OBJECTS
#define PROBLEM_MAX_WEIGHT 269
#define POPULATION_SIZE 100
#define GENERATIONS 100
#define TOURNMENT_PARTICIPANTS 5
#define MUTATION_RATE 0.05
#define TRUE 1
#define FALSE 0

#endif